using System.ComponentModel.DataAnnotations;

namespace Dispatch
{
    [MetadataType(typeof(Employee_HistoryMetadata))]
    public partial class Employee_HistoryEntity
    {
        #region Properties
        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 3, 2017
        ///----------------------------
        public int Id { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 3, 2017
        ///----------------------------
        public int EmployeeId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 3, 2017
        ///----------------------------
        public int DepartmentId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 3, 2017
        ///----------------------------
        public int Position { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 3, 2017
        ///----------------------------
        public System.DateTime TimeIn { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 3, 2017
        ///----------------------------
        public System.DateTime TimeOut { get; set; }

        public string Note { get; set; }

        #endregion
    }
}
