using System;
using System.ComponentModel.DataAnnotations;

namespace Dispatch
{
    //[MetadataType(typeof(Project_RoleMetadata))]
    public partial class Project_RoleEntity
    {
        #region Properties
        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public int UserId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public int ProjectId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public bool Add { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public bool Edit { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public bool View { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public bool Delete { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public bool Print { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 13, 2017
        ///----------------------------
        public bool ViewPrice { get; set; }

        public int Position { get; set; }


        #endregion
    }
}

