using System;
using System.ComponentModel.DataAnnotations;

namespace Dispatch
{
    
    public partial class ProjectEntity
    {
        #region Properties
        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        public long Id { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
        [Required(ErrorMessage = "Chưa chọn tên dự án")]
        public string Name { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
        [Required(ErrorMessage = "Chưa chọn khách hàng")]
        public int CustomerId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
        [Required(ErrorMessage = "Chưa điền giá")]
        public string Price { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///

        [Range(1, int.MaxValue, ErrorMessage = "Chưa chọn Sales")]
        public int SalesId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
        [Required(ErrorMessage = "Chưa điền thông tin")]
        public string Description { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        public System.DateTime CreateDate { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        public System.DateTime ModifiedDate { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        public bool IsDel { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
        [Required(ErrorMessage = "Chưa chọn trạng thái")]
        [Range(1, int.MaxValue, ErrorMessage = "Chưa chọn trạng thái")]
        public int StatusId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
        [Required(ErrorMessage = "Chưa chọn lĩnh vực")]
        [Range(1, int.MaxValue, ErrorMessage = "Chưa chọn lĩnh vực")]
        public int TypeId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
       
        
        public string ListManager { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
       
        public string ListTechnical { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
      
        public string ListAssistant { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: April 12, 2017
        ///----------------------------
        ///
      
        public string ListBuyer { get; set; }

        #endregion
    }
}

