using System;

namespace Dispatch
{
	public partial class FileEntity
	{
		#region Properties
		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the Id value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public long Id { get; set; }

		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the UserId value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public int UserId { get; set; }

		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the Name value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the MimeType value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public string MimeType { get; set; }

		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the FileSize value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public string FileSize { get; set; }

		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the IsDel value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public bool IsDel { get; set; }

		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the Private value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public bool Private { get; set; }

		/// <summary>
		/// MinhDuongVan generator
		/// Gets or sets the UploadDate value.
		/// 2017-02-16 15:28:25Z
		/// </summary>
		public DateTime UploadDate { get; set; }
        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 9, 2017
        ///----------------------------
        public int DispatchId { get; set; }

        ///----------------------------
        /// Generated By:   Sushi-Sashimi using CodeSmith 6.0.0.0
        /// Template:       TableEntity.cst
        /// Date Generated: March 9, 2017
        ///----------------------------
        public bool Type { get; set; }
        #endregion
    }
}
